### ISSUE TITLE
Skip deleting trunk branch

### ISSUE THREAD

**Issue by pritamrungta** [HaywardMorihara/gh-tidy#41]
Hi! In my case, I have some PRs from `main -> dev` branches for keeping those up to date.
Is it possible to wrap the entire contents below in a condition like (branch != trunk_branch)
https://github.com/HaywardMorihara/gh-tidy/blob/b1c79a6e1b3d9fa3b7273a55df4c9da2da191d05/gh-tidy#L136-L144

**Comment by HaywardMorihara** [comment]
Hey!

So you're saying you sometimes have branches where you're merging changes from `main` (the trunk branch) _into_ a development branch?

**Comment by pritamrungta** [comment]
yes, correct.
just to keep dev synchronized

**Comment by HaywardMorihara** [comment]
Oops, yup that's what I meant haha

Okay, yeah I think that makes sense. I might be able to get to this soon, but feel free to push up a pull request with the change.

Long-Term Though-To-Self: Would be nice to be able to configure "protected branches" for your repo that would never be automatically deleted

**Comment by pritamrungta** [comment]
Yeah, protected-branch support sounds great (especially if it is configurable through a flag)

I have created #42 for trunk branch check in the meantime

**Comment by HaywardMorihara** [comment]
Approved & merged! Thank you!
