### ISSUE TITLE
Error attempting to prune local branches

### ISSUE THREAD

**Issue by HerbWarren** [HaywardMorihara/gh-tidy#46]
Pretty likely that someone's used some unexpected characters in branch names.

I'm getting an error attempting to tidy a repo:
```
Pruning local branches that show as 'merged' to local ...
fatal: malformed object name --format=%(refname:short)
```

If there is some way to get more info -- like what the branch name is that's causing trouble -- that would be super-helpful. There's no more information, and tidy continues on (yay!).

**Comment by HaywardMorihara** [comment]
Hi @HerbWarren!

Does the repo you used this on have a `main` or `master` branch as it's trunk branch? I played around with this a bit, and I'm guessing it does _not_ and that is why the error is happening:

```sh
@HaywardMorihara ➜ /workspaces/gh-tidy (main) $ trunk_branch=
@HaywardMorihara ➜ /workspaces/gh-tidy (main) $ git branch --merged $trunk_branch --format='%(refname:short)'
fatal: malformed object name --format=%(refname:short)
@HaywardMorihara ➜ /workspaces/gh-tidy (main) $ git branch --merged main --format='%(refname:short)'
main
@HaywardMorihara ➜ /workspaces/gh-tidy (main) $ git branch --merged master --format='%(refname:short)'
fatal: malformed object name master
```

You can see the line where this command is executed [here](https://github.com/HaywardMorihara/gh-tidy/blob/main/gh-tidy#L132)

**Comment by HerbWarren** [comment]
Ah -- that also explains this line of output that I should have guessed was related:
```Determined '' as the trunk branch```

We do have a `master` branch on this repo, so that's a little odd, but the default branch is `develop`

**Comment by HaywardMorihara** [comment]
Nah, let's do it! Let's add support for `develop`! I was actually working in another repo that has `develop` as the trunk branch and wasn't able to use this because of it so was thinking I should make this more flexible anyway. And support other potential branches as the trunk. 

Also, maybe a more helpful error message if it isn't finding an appropriate trunk.

I'll try to get to it this weekend, or feel free to take a crack at it yourself and submit a pull request!

**Comment by spoilsportmotors** [comment]
I didn't address the "more helpful error message" part, just the bare minimum to let someone specify their own trunk branch.

**Comment by HaywardMorihara** [comment]
> I made a couple of other tiny changes to help people find/use the new trunk option.

Awesome, thank you! Requested a couple of changes on the PR

**Comment by HaywardMorihara** [comment]
Thought: this is a place where https://github.com/HaywardMorihara/gh-tidy/issues/43 would be nice
